[package]
name = "proxy-wasm-experimental"
version = "0.0.8"
authors = ["Piotr Sikora <piotrsikora@google.com>", "Yaroslav Skopets <yaroslav@tetrate.io>"]
description = "WebAssembly for Proxies"
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/yskopets/proxy-wasm-rust-sdk"
edition = "2018"

[features]
wee-alloc = ["wee_alloc"]

[dependencies]
hashbrown = "^0.11.2"
log = "0.4"
wee_alloc = { version = "0.4", optional = true }

[dev-dependencies]
version-sync = "0.9"
cfg-if = "1.0"
chrono = "0.4"
bstr = "0.2"

[target.'cfg(not(all(target_arch = "wasm32", target_os = "unknown")))'.dev-dependencies]
getrandom = "0.2"

[profile.release]
lto = true
opt-level = 3
panic = "abort"

[package.metadata.raze]
workspace_path = "//bazel/cargo"
genmode = "Remote"

[package.metadata.raze.crates.getrandom.'=0.2.0']
gen_buildrs = true

[package.metadata.raze.crates.libc.'=0.2.85']
gen_buildrs = true

[package.metadata.raze.crates.log.'=0.4.14']
gen_buildrs = true

[[example]]
name = "hello_world"
path = "examples/hello_world.rs"
crate-type = ["cdylib"]

[[example]]
name = "http_auth_random"
path = "examples/http_auth_random.rs"
crate-type = ["cdylib"]

[[example]]
name = "http_headers"
path = "examples/http_headers.rs"
crate-type = ["cdylib"]

[[example]]
name = "http_body"
path = "examples/http_body.rs"
crate-type = ["cdylib"]

[[example]]
name = "http_config"
path = "examples/http_config.rs"
crate-type = ["cdylib"]
